[package]
name = "vsc-core-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.vsc]
path = ".."
package = "vsc-core"

# Prevent this from interfering with workspace members up the tree.
[workspace]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_catalog"
path = "fuzz_targets/fuzz_catalog.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_store"
path = "fuzz_targets/fuzz_store.rs"
test = false
doc = false
bench = false
